### ISSUE TITLE
Cannot initialize ScollBar programmatically

### ISSUE THREAD

**Issue by Antimonit** [turing-tech/MaterialScrollBar#121]
Calling non-XML constructor programmatically:
```
DragScrollBar(context, recyclerView, lightOnTouch)
```
results into an exception:
```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.res.TypedArray.hasValue(int)' on a null object reference
        at com.turingtechnologies.materialscrollbar.MaterialScrollBar.implementPreferences(MaterialScrollBar.java:188)
        at com.turingtechnologies.materialscrollbar.MaterialScrollBar.generalSetup(MaterialScrollBar.java:245)
        at com.turingtechnologies.materialscrollbar.MaterialScrollBar.<init>(MaterialScrollBar.java:115)
        at com.turingtechnologies.materialscrollbar.DragScrollBar.<init>(DragScrollBar.java:38)
        at com.example.screens.main.MainLayout.createView(MainLayout.kt:70)
        ...
```

**Comment by turing-tech** [comment]
Reproduced. I will work on fixing this asap.
