### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Rainer-Lang** [turing-tech/MaterialScrollBar#27]
java.lang.NullPointerException: Attempt to read from field 'float android.graphics.RectF.left' on a null object reference
    at android.graphics.Canvas.drawArc(Canvas.java:1197)
    at com.turingtechnologies.materialscrollbar.Handle.onDraw(Handle.java:90)
    at android.view.View.draw(View.java:16184)
    at android.view.View.updateDisplayListIfDirty(View.java:15180)
    at android.view.View.draw(View.java:15954)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
    at android.view.View.updateDisplayListIfDirty(View.java:15175)
    at android.view.View.draw(View.java:15954)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
    at android.view.View.draw(View.java:16187)
    at android.view.View.updateDisplayListIfDirty(View.java:15180)
    at android.view.View.draw(View.java:15954)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
    at android.view.View.updateDisplayListIfDirty(View.java:15175)
    at android.view.View.draw(View.java:15954)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
    at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1077)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
    ...

**Comment by Rainer-Lang** [comment]
What info do you need?

**Comment by turing-tech** [comment]
@Rainer-Lang The code for the instantiation of the scroll bar would be helpful. Does this always happen or only when certain actions are taken?

**Comment by Rainer-Lang** [comment]
`new MyMaterialScrollBar(getContext(), mRecyclerView, true);`

with

```
public class MyMaterialScrollBar extends DragScrollBar {

    public MyMaterialScrollBar(Context context, RecyclerView recyclerView, boolean lightOnTouch) {
        super(context, recyclerView, lightOnTouch);

        this.setBarColour(App.colorAccentLight);
        this.setHandleColour(App.colorAccent);
        this.setHandleOffColour(App.colorAccent);
        this.addIndicator(new AlphabetIndicator(context), true);
    }
}
```

It's in a fragment.

It happens always.

**Comment by turing-tech** [comment]
Are you overriding any of the DragScrollBar methods?

**Comment by Rainer-Lang** [comment]
no

**Comment by Rainer-Lang** [comment]
@krimin-killr21 Got the error -> solutions

changed the layout.xml
I had a RelativeLayout around the RV. Then I deleted the RelativeLayout and I got the error.

**Comment by turing-tech** [comment]
OK, cool. Glad it worked out.

**Comment by Rainer-Lang** [comment]
Sorry for this....

FYI: I have
- CoordinatorLayout
  --- FrameLayout
  ----- SwipeRefreshLayout
  ------- RelativeLayout
  --------- RecyclerView
