### ISSUE TITLE
Error on setting handle colour

### ISSUE THREAD

**Issue by createS0ftware** [turing-tech/MaterialScrollBar#58]
HI 

I keep getting the error :

"  java.lang.ClassCastException: android.graphics.drawable.BitmapDrawable cannot be cast to android.graphics.drawable.GradientDrawable
                                                                            at com.turingtechnologies.materialscrollbar.Indicator.linkToScrollBar(Indicator.java:74)
                                                                            at com.turingtechnologies.materialscrollbar.MaterialScrollBar$2.onLayoutChange(MaterialScrollBar.java:547)
                                                                            at android.view.View.layout(View.java:16645)"

What am i missing - the code is almost identical to the demo code

Thanks

**Comment by createS0ftware** [comment]
In the Indicator class it always seems to find Bitmap drawable as the background though it is setting the same one in the demo app as in my app

**Comment by createS0ftware** [comment]
It's ok i had a duplicate name drawable
