### ISSUE TITLE
Crash when hidden header

### ISSUE THREAD

**Issue by phantuanphong** [turing-tech/MaterialScrollBar#78]
java.lang.ArithmeticException: divide by zero
                                                                             at com.turingtechnologies.materialscrollbar.ScrollingUtilities.scrollToPositionAtProgress(ScrollingUtilities.java:116)
                                                                             at com.turingtechnologies.materialscrollbar.MaterialScrollBar.onDown(MaterialScrollBar.java:686)
                                                                             at com.turingtechnologies.materialscrollbar.DragScrollBar$1.onTouch(DragScrollBar.java:79)
                                                                             at android.view.View.dispatchTouchEvent(View.java:9290)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                             at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
                                                                             at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                             at android.view.View.dispatchPointerEvent(View.java:9514)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                             at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                             at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                             at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                             at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                             at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                         	at android.os.MessageQueue.nativePoll

**Comment by turing-tech** [comment]
I'm going to need a better explain than that.

**Comment by phantuanphong** [comment]
I have a row ( as header of recylerView), i set GONE for this row. When i use fast scroll of this LIB and it will crash.

```
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {

        if (viewType == TYPE_ITEM) {
            View itemView = inflater.inflate(R.layout.item_song, parent, false);
            return new MyViewHolder(itemView);
        } else if (viewType == TYPE_HEADER) {
            View itemView = inflater.inflate(R.layout.native_express_ad_container, parent, false);
            
            // hide row
            if( isHidden ){
                itemView.setVisibility(View.GONE);
            }

            return new NativeExpressAdViewHolder(itemView);
        }
        throw new RuntimeException("there is no type that matches the type " + viewType + " + make sure your using types correctly");
    }
```

**Comment by turing-tech** [comment]
Are you using the latest version of the library? Line 116 of ScrollingUtilities is a commented line in the latest release. It probably won't fix your problem, but I can't debug a version of the library that I don't have in front of me.
